<?php

namespace AppBundle\Repository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByImage($imageName)
    {
        return
            $this->createQueryBuilder('qb')
                ->join('qb.image', 'image')
                ->where('image.path = :path')
                ->setParameter('path', $imageName)
                ->orderBy('qb.dateCreate', 'DESC')
                ->getQuery()
                ->getResult();
    }
}
