<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityNotFoundException;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getImagesByUser($userId)
    {
        return
            $this->createQueryBuilder('qb')
                ->join('qb.user','u')
                ->where('u.id = :userId')
                ->setParameter('userId', $userId)
                ->getQuery()
                ->getResult();
    }

    public function deleteByPath($path)
    {
        return
            $this->createQueryBuilder('qb')
                ->delete()
                ->where('qb.path = :path')
                ->setParameter('path', $path)
                ->getQuery()
                ->getResult();
    }

    public function getByPath($path)
    {
        $qb = $this->createQueryBuilder('qb')
                ->where('qb.path = :path')
                ->setParameter('path', $path)
                ->getQuery();

        try{
            return $qb->getSingleResult();
        } catch(\Exception $e) {
            return null;
        }
    }
}
